export { default as Home } from "./Home";
export { default as FullPost } from "./FullPost";
export { default as AddPost } from "./AddPost";
export { default as Registration } from "./Registration";
export { default as Login } from "./Login";
export { default as MyPosts } from "./MyPosts";
export { default as Favorites } from "./Favorites";
export { default as Admin } from "./Admin";
export { default as MyAccount } from "./MyAccount";
